learn/urls.py
from django.conf.urls import patterns, url
from learn import views

app_name = 'learn' 
urlpatterns = patterns('',
    url(r'^$', views.login, name='login'),
    url(r'^login/$',views.login,name = 'login'),
    url(r'^regist/$',views.regist,name = 'regist'),
    url(r'^index/$',views.index,name = 'index'),
    url(r'^logout/$',views.logout,name = 'logout'),
)

myword/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
	url(r'^$', 'learn.views.index', name='index'),
	url(r'^function/(?P<function_slug>[^/]+)/$', 'learn.views.function_detail', name='function'),
	url(r'^column/(?P<column_slug>[^/]+)/$', 'learn.views.column_detail', name='column'),
	url(r'^word/(?P<pk>\d+)/(?P<word_slug>[^/]+)/$', 'learn.views.word_detail', name='word'),
	url(r'^function/danci/bdc/$', 'learn.views.bdc', name='bdc'),
	url(r'^function/(?P<function_slug>[^/]+)/reset/$', 'learn.views.reset', name='reset'),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^accounts/', include('learn.urls')),
]

learn/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
 
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.core.urlresolvers import reverse
import datetime
@python_2_unicode_compatible
class Function(models.Model):
    name = models.CharField('功能', max_length=256,unique=True)
    slug = models.CharField('功能网址', max_length=256, db_index=True,unique=True)
    intro = models.TextField('功能简介', default='')
    nav_display = models.BooleanField('导航显示', default=True)
    home_display = models.BooleanField('首页显示', default=True) 
    def __str__(self):
        return self.name
 
    class Meta:
        verbose_name = '功能'
        verbose_name_plural = '功能'
        ordering = ['name']  # 按照哪个栏目排序
        
    def get_absolute_url(self):
        return reverse('function', args=(self.slug,))
        
@python_2_unicode_compatible
class Column(models.Model):
    function = models.ManyToManyField(Function, verbose_name='归属功能')
    name = models.CharField('分类', max_length=256,unique=True)
    slug = models.CharField('分类网址', max_length=256,db_index=True,unique=True)
    intro = models.TextField('分类简介', default='')
#    nav_display = models.BooleanField('导航显示', default=False)
#    home_display = models.BooleanField('首页显示', default=False) 
    def __str__(self):
        return self.name
 
    class Meta:
        verbose_name = '分类'
        verbose_name_plural = '分类'
        
    def get_absolute_url(self):
        return reverse('column', args=(self.slug,))
 
 
@python_2_unicode_compatible
class Word(models.Model):
    column = models.ManyToManyField(Column, verbose_name='归属分类')
    name = models.CharField('单词', max_length=256)
    slug = models.CharField('网址', max_length=256, db_index=True)
#    comment = models.TextField('笔记', default='', blank=True)
#    author = models.ForeignKey('auth.User', blank=True, null=True, verbose_name='作者')
    content = models.TextField('内容', default='', blank=True)
 
    def __str__(self):
        return self.name
 
    class Meta:
        verbose_name = '单词'
        verbose_name_plural = '单词'
        
    def get_absolute_url(self):
        return reverse('word', args=(self.pk, self.slug))
    
@python_2_unicode_compatible        
class User(models.Model):
    username = models.CharField(max_length=50,unique=True)
    password = models.CharField(max_length=50)
    column = models.CharField(default='六级',max_length=256)
    count = models.IntegerField(default=20)
    daka = models.IntegerField(default=0)
    date=models.DateField('时间',null=True,default=datetime.date(2012, 12, 7))
    class Meta:
        verbose_name = '用户'
        verbose_name_plural = '用户'
    def __str__(self):
        return self.username
        

@python_2_unicode_compatible
class Comment(models.Model):
    wordfor = models.ManyToManyField(Word, verbose_name='归属单词')
    author = models.CharField('作者', max_length=50,)

    content = models.TextField('内容', default='', blank=True)
 
    def __str__(self):
        return self.content
 
    class Meta:
        verbose_name = '笔记'
        verbose_name_plural = '笔记'

learn/forms.py
from django import forms
 
class CommentForm(forms.Form):
    comment = forms.CharField()

learn/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render,redirect,render_to_response
from django.http import HttpResponse,HttpResponseRedirect
from django.template import RequestContext
from django import forms
from learn.models import Column,Word,Function,User,Comment
from learn.forms import CommentForm
import datetime

def index(request):
    home_display_functions = Function.objects.filter(home_display=True)
    nav_display_functions = Function.objects.filter(nav_display=True)
    username,flag=get_session(request)
    return render(request, 'index.html', {
        'home_display_functions': home_display_functions,
        'nav_display_functions': nav_display_functions,
        'flag':flag,
        'username':username
    })

def get_session(request):
    flag=False
    if 'user_name' in request.session:
        username=request.session["user_name"]
        flag=True
    else:
        username=''
    return username,flag

class ColumnForm(forms.Form):
    column=forms.CheckboxInput()
    count=forms.CharField()

    
def function_detail(request, function_slug):
    function = Function.objects.get(slug=function_slug)
    username,flag=get_session(request)
    user=None
    cf=''
    count_list=[50,100,150]
    if flag:
        user = User.objects.get(username__exact = username)
        if request.method == 'POST':
#            cf = ColumnForm(request.POST)
#            if cf.is_valid():
            new_column = request.POST['choice']
            new_count = request.POST['count']
            user.column=new_column
            user.count=new_count
            user.save()
        else:
            cf = ColumnForm()
    home_display_functions = Function.objects.filter(home_display=True)
    nav_display_functions = Function.objects.filter(nav_display=True)
    return render(request, 'learn/function.html', {'function': function,
                                                   'user':user,
                                                   'flag':flag,
                                                   'cf':cf,
                                                   'username':username,
                                                   'count_list':count_list,
                                                 'home_display_functions': home_display_functions,
                                                 'nav_display_functions': nav_display_functions,})
 
def column_detail(request, column_slug):
    column = Column.objects.get(slug=column_slug)
    username,flag=get_session(request)
    home_display_functions = Function.objects.filter(home_display=True)
    nav_display_functions = Function.objects.filter(nav_display=True)
    return render(request, 'learn/column.html', {'column': column,
                                                 'flag':flag,
                                                 'username':username,
                                                 'home_display_functions': home_display_functions,
                                                 'nav_display_functions': nav_display_functions,})
 
 
def word_detail(request, pk, word_slug):
    word = Word.objects.get(pk=pk)
    username,flag=get_session(request)
    comment_all=Comment.objects.filter(wordfor= word)
    comment_my=Comment.objects.filter(wordfor= word,author=username)
    home_display_functions = Function.objects.filter(home_display=True)
    nav_display_functions = Function.objects.filter(nav_display=True)
    if request.method == 'POST':
        comment = CommentForm(request.POST)
        if comment.is_valid():
            
            a = comment.cleaned_data['comment']
            comment=Comment.objects.get_or_create(author=username,content=a)[0]
            comment.wordfor.add(word)

#            return render(request, 'learn/word.html', {'word': word,
#                                                   'form': comment,
#                                                   'comment_all':comment_all,
#                                                   'comment_my':comment_my,
#                                                   'home_display_functions': home_display_functions,
#                                                   'nav_display_functions': nav_display_functions,})
    else:
        comment = CommentForm()
    return render(request, 'learn/word.html', {'word': word,
                                               'form': comment,
                                               'comment_all':comment_all,
                                               'comment_my':comment_my,
                                               'flag':flag,
                                               'username':username,
                                               'home_display_functions': home_display_functions,
                                               'nav_display_functions': nav_display_functions,})

def bdc(request):
    home_display_functions = Function.objects.filter(home_display=True)
    nav_display_functions = Function.objects.filter(nav_display=True)
    username,flag=get_session(request)    
    if flag:
        daka_flag=False
        user = User.objects.get(username__exact = username)
        column_name=user.column
        count=user.count
        daka=user.daka
        column = Column.objects.get(name=column_name)
        words=column.word_set.all()[daka*count:(daka+1)*count]
        if (datetime.date.today()-user.date).days<1:
            daka_flag=True
            
        else:
            daka_flag=False
        if request.method == 'POST':
            user.daka=user.daka+1
            user.date=datetime.date.today()
            user.save()
            daka_flag=True
        return render(request, 'learn/bdc.html', {'words': words,
                                                  'count':count,
                                                  'daka_flag':daka_flag,
                                                  'flag':flag,
                                                 'username':username,
                                                 'home_display_functions': home_display_functions,
                                                 'nav_display_functions': nav_display_functions,})                                                 


def reset(request, function_slug):
    function = Function.objects.get(slug=function_slug)
    username,flag=get_session(request)
    user=None
    cf=''
    count_list=[50,100,150]
    if flag:
        user = User.objects.get(username__exact = username)
        if request.method == 'POST':
#            cf = ColumnForm(request.POST)
#            if cf.is_valid():
            new_column = request.POST['choice']
            new_count = request.POST['count']
            user.column=new_column
            user.count=new_count
            user.save()
        else:
            cf = ColumnForm()
    home_display_functions = Function.objects.filter(home_display=True)
    nav_display_functions = Function.objects.filter(nav_display=True)
    return render(request, 'learn/reset.html', {'function': function,
                                                   'user':user,
                                                   'flag':flag,
                                                 'username':username,
                                                   'cf':cf,
                                                   'count_list':count_list,
                                                 'home_display_functions': home_display_functions,
                                                 'nav_display_functions': nav_display_functions,})
                                                 
class UserForm(forms.Form): 
    username = forms.CharField(label='用户名',max_length=100)
    password = forms.CharField(label='密码',widget=forms.PasswordInput())



def regist(request):

    nav_display_functions = Function.objects.filter(nav_display=True)
    if request.method == 'POST':
        uf = UserForm(request.POST)
        if uf.is_valid():
            #获得表单数据
            username = uf.cleaned_data['username']
            password = uf.cleaned_data['password']
            #添加到数据库
            User.objects.get_or_create(username= username,password=password)
            return HttpResponseRedirect('/accounts/login/')
    else:
        uf = UserForm()
    return render_to_response('regist.html',{'uf':uf,'nav_display_functions': nav_display_functions,}, context_instance=RequestContext(request))


def login(request):
    nav_display_functions = Function.objects.filter(nav_display=True)
    if request.method == 'POST':
        uf = UserForm(request.POST)
        if uf.is_valid():
            #获取表单用户密码
            username = uf.cleaned_data['username']
            password = uf.cleaned_data['password']
            #获取的表单数据与数据库进行比较
#            m = User.objects.get(username=request.POST['username'])
            user = User.objects.filter(username__exact = username,password__exact = password)
            if user:
                #比较成功，跳转index
                response = HttpResponseRedirect('/')
                #将username写入浏览器cookie,失效时间为3600
#                response.set_cookie('username',username,3600)
                request.session['user_name'] = username
                return response
            else:
                #比较失败，还在login
                return HttpResponseRedirect('/accounts/login/')
    else:
        uf = UserForm()
    return render_to_response('login.html',{'uf':uf,'nav_display_functions': nav_display_functions,},context_instance=RequestContext(request))


def logout(request):
    try:
        del request.session['user_name']
    except KeyError:
        pass
#    return HttpResponse("You're logged out.")
    return HttpResponseRedirect('/accounts/login/')

learn/templates/learn/bdc.html
{% extends "base.html" %}
 
{% block title %}
背单词
{% endblock title %}
 
 
{% block content %}


今天需要完成的单词：
<ul>
	{% if daka_flag %}
		<p>今日已打过卡，明天再来哦</p>
	{% else %}
		{% for word in words %}
			<li>
				<a href="{{ word.get_absolute_url }}">{{ word.name }}</a>
			</li>
		{% endfor %}
		<form action="." class="form-horizontal" method="POST">
			{% csrf_token %}
			<input type="submit" value="已背完，去打卡" class="btn btn-primary">

		</form>
	{% endif %}
    
</ul>
{% endblock content %}

learn/templates/learn/column.html
{% extends "base.html" %}
 
{% block title %}
{{ column.title }}
{% endblock title %}
 
 
{% block content %}

<p>分类名称：{{ column.name }}</p>
分类单词列表：
<ul>
    {% for word in column.word_set.all %}
        <li>
            <a href="{{ word.get_absolute_url }}">{{ word.name }}</a>
        </li>
    {% endfor %}
</ul>
{% endblock content %}

learn/templates/learn/function.html
{% extends "base.html" %}
 
{% block title %}
{{ function.name }}
{% endblock title %}
 
{% block content %}
<div class="col-xs-6 col-sm-1">
</div>
<div class="col-xs-6 col-sm-3">
{% ifequal function.name "单词" %}
{% if flag %}

        <p>你选择了背诵：{{ user.column }}</p>
		<p>每天单词数：{{ user.count }}</p>
		<a href="bdc"><input type="button" value="去背单词" class="btn btn-success"></a>
		<a href="reset"><input type="button" value="重新设置" class="btn btn-success" id='reset'></a>



{% else %}
	<p>还没有登陆哦，去首页登陆吧</p>
{% endif %}
{% else %}
{% endifequal %}
</div>
{% endblock content %}

learn/templates/learn/reset.html
{% extends "base.html" %}
 
{% block title %}
重设模式
{% endblock title %}
 
 
{% block content %}
{% ifequal function.name "单词" %}
{% if flag %}
<div class="col-xs-6 col-sm-1">
</div>
<div class="col-xs-6 col-sm-2">
<form  method="post">
{% csrf_token %}

<p>选择背诵：</p>
{% for column in function.column_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ column.name }}" />
    <label for="choice{{ forloop.counter }}">{{  column.name  }}</label><br />
{% endfor %}
</div>
<div class="col-xs-6 col-sm-2">
<p>每天单词数量：</p>
{% for count in count_list %}
    <input type="radio" name="count" id="choice{{ forloop.counter }}" value="{{ count }}" />
    <label for="choice{{ forloop.counter }}">{{  count  }}</label><br />
{% endfor %}
<input type="submit" value="确定" />
</form>

{% else %}
	<p>还没有登陆哦，去首页登陆吧</p>
{% endif %}
{% else %}
{% endifequal %}
</div>
<div class="col-xs-6 col-sm-1">
</div>
<div class="col-xs-6 col-sm-3">
        <p>你选择了背诵：{{ user.column }}</p>
		<p>每天单词数：{{ user.count }}</p>
		<a href="http://127.0.0.1:8000/function/danci"><input type="button" value="返回" class="btn btn-success"></a>
</div>
{% endblock content %}

learn/templates/learn/word.html
{% extends "base.html" %}

{% block title %}
{{ word.name }}
{% endblock title %}
 
 
{% block content %}
<style>
h1
{
color:#209e85;
text-align:center;
}
h3
{
color:#209e85;
text-align:center;
}
p
{

font-family:"Times New Roman";
font-size:18px;
}
</style>

        <h1 class="text-center">单词：{{ word.name }}</h1>

        <h3 class="text-center">{{ word.content }}</h3>


<div class="container">
   <div class="row" >
	<div class="col-xs-6 col-sm-1">
	</div>
      <div class="col-xs-6 col-sm-3">
        <p>共享笔记:</p>
        {% for comment in comment_all %}
			<p>笔记内容：{{ comment.content }}</p>
			<p>作者：{{ comment.author }}</p>
			<p>****************************************************</p>
		{% endfor %}
		</div>
		<div class="col-xs-6 col-md-offset-2">
        <p>我的笔记:</p>
        {% for comment in comment_my %}
			<p>笔记内容：{{ comment.content }}</p>
			<p>-----作者：{{ comment.author }}</p>
			<p>****************************************************</p>
		{% endfor %}
		
			<form method='post'>
			{% csrf_token %}

			{{ form }}
			<input type="submit" value="添加我的笔记">
			</form>
			<a href="http://127.0.0.1:8000/function/danci/bdc/"><input type="button" value="返回去背下一个" class="btn btn-success"></a>
			</div>
</div>
</div>

{% endblock content %}